### ISSUE TITLE
Script for scraping eve-incursions.de

### ISSUE THREAD

**Issue by kennethjor** [autonomouslogic/eve-ref#333]
[eve-incursions.de](https://eve-incursions.de/) has Incursion data going back quite a while. Write a script to scrape all the data on the [API](https://eve-incursions.de/api) and package it up in a file to supplement the [existing Incursion data](https://data.everef.net/incursions/).

This will be a one-off script for scraping the data for backfill, as there already exists a regular job to scrape the data from the ESI.

* [x] Get permission from original author
* [x] Write script
* [x] Run script
* [x] Upload file
* [x] Update docs with notes on where the data came from

**Comment by kennethjor** [comment]
@joaomlneto provided a curl command:
```shell
curl -X POST -H 'content-type: application/json' https://eve-incursions.de/api --data "{\"query\":\"query{spawnLogs(page: $PAGE){items{id date state spawn {id establishedAt endedAt state constellation {id} influenceLogs{id date influence}}}}}\"}"
```
The number of pages is unknown. Eventually, the API return an empty array.

**Comment by joaomlneto** [comment]
To scrape each page at 10 second intervals:
```bash
#!/usr/bin/env bash

NUM_PAGES=559

for PAGE in $( eval echo {1..$NUM_PAGES} )
do
  echo "Fetching page $PAGE of $NUM_PAGES"
  curl -s -X POST -H 'content-type: application/json' https://eve-incursions.de/api --data "{\"query\":\"query{spawnLogs(page: $PAGE){items{id date state spawn {id establishedAt endedAt state constellation {id} influenceLogs{id date influence}}}}}\"}" > $PAGE.json
  sleep 10
done
```


To then merge them all into a single file with NodeJS:
```js
const fs = require('fs');
const files = fs.readdirSync(".").filter(filename => filename.endsWith(".json"));
const contents = files.map(filename => JSON.parse(fs.readFileSync(filename)))
	.flatMap(contents => contents.data.spawnLogs.items)
console.log(JSON.stringify(contents, null, 2))
```

The result is a 158MB JSON file. Maybe not ideal? But don't know how to convert it. An excerpt of the format below:

```json
[
  {
    "id": "11244",
    "date": "2023-10-10T17:35:00.000Z",
    "state": "Mobilizing",
    "spawn": {
      "id": "3337",
      "establishedAt": "2023-10-09T04:30:00.000Z",
      "endedAt": null,
      "state": "Mobilizing",
      "constellation": {
        "id": "20000520"
      },
      "influenceLogs": [
        {
          "id": "364299",
          "date": "2023-10-09T05:00:00.000Z",
          "influence": 0
        },
        …
        {
          "id": "364548",
          "date": "2023-10-11T10:00:00.000Z",
          "influence": 1
        }
      ]
    }
  },
  …
]
```

**Comment by kennethjor** [comment]
File available at https://data.everef.net/incursions/history/backfills/eve-incursions-de-2023-10-12.json.xz
