### ISSUE TITLE
Reference Data > Market Groups > Blank localised names and descriptions

### ISSUE THREAD

**Issue by dangarfield** [autonomouslogic/eve-ref#355]
A number of localised data points in the `reference-data` are incorrectly blank. I see this mainly in `market groups`, but there may be other types, it doesn't appear to an issue in `types`

The are correct in SDE, but it is assumed that the ESI response contain blank fields and therefore are overriding them.

New suggested behaviour:
- If the content from the ESI for the localised fields is blank, do not update the reference data with the ESI content

**Comment by kennethjor** [comment]
Fixed in the legacy code too.
