### ISSUE TITLE
Kernite's enormous mass value messes up layout

### ISSUE THREAD

**Issue by joaomlneto** [autonomouslogic/eve-ref#387]
Kernite is well-known[citation needed] to have a huge density of 10^35 kg per 1.2m^3.

However, displaying it in its full glory causes some issues with the layout.

https://everef.net/type/20

**Comment by kennethjor** [comment]
![image](https://github.com/autonomouslogic/eve-ref/assets/289163/ca7e003c-fee3-48fc-8c08-c0b9be1a5128)

**Comment by kennethjor** [comment]
Fixed on legacy, will be deployed on the next build.
