### ISSUE TITLE
Reference data fetch in Nuxt via OpenAPI

### ISSUE THREAD

**Issue by kennethjor** [autonomouslogic/eve-ref#83]
Depends on #95 

The API is being generated in the UI, but the base API classes aren't being used, only the models.

**Comment by terrarum** [comment]
@kennethjor nuxt needs to use its `useFetch` method to ensure that requests work in both client and server environments so I don't think we can use the generated classes.

**Comment by kennethjor** [comment]
An experiment I wasn't able to make work, FWIW
```
  class UseFetchHttpLibrary implements PromiseHttpLibrary {
    async send(request: RequestContext): Promise<ResponseContext> {
      const response = await useFetch(request.getUrl());
      return {
        httpStatusCode: response.statusCode,
        body: response.data
      };
    }
  }
  const api = new RefdataApi({
    httpApi: wrapHttpLibrary(new UseFetchHttpLibrary())
  } as Configuration);
  const api = new RefdataApi({});

  const route = useRoute();
  const id = parseInt(route.params.id);

  if (!id) {
    console.error('id is null');
  }

  // const response = await useFetch(`https://ref-data.everef.net/types/${id}`);
  const response = await api.getType(id);
  const inventoryType: InventoryType = response as InventoryType;
```

**Comment by kennethjor** [comment]
The `typescript-fetch` generator has this bit in its `runtime.ts`:
![image](https://github.com/autonomouslogic/eve-ref/assets/289163/b8541575-5fb5-4537-9a65-436d7ab3d838)
which seems to imply you can swap out the actual HTTP API for something else.
